"""adiciona forma_pagamento e endereco_entrega em pedido

Revision ID: 4c71a3aace8f
Revises: 800873833bce
Create Date: 2026-09-02 22:51:47.936731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c71a3aace8f'
down_revision = '800873833bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('endereco_entrega', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('endereco_entrega')
        batch_op.drop_column('forma_pagamento')

    # ### end Alembic commands ###
