"""adiciona canal e chatwoot_conversation_id em conversa_estado

Revision ID: 800873833bce
Revises: b4522ada3d3e
Create Date: 2026-08-26 20:41:20.272943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800873833bce'
down_revision = 'b4522ada3d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversa_estado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('chatwoot_conversation_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversa_estado_chatwoot_conversation_id'), ['chatwoot_conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversa_estado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversa_estado_chatwoot_conversation_id'))
        batch_op.drop_column('chatwoot_conversation_id')
        batch_op.drop_column('canal')

    # ### end Alembic commands ###
