"""adiciona configuracao_loja

Revision ID: b4522ada3d3e
Revises: f8e1a22f08c0
Create Date: 2026-08-26 04:03:19.763493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4522ada3d3e'
down_revision = 'f8e1a22f08c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_loja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto_saudacao', sa.String(length=1000), nullable=True),
    sa.Column('texto_menu_comprar', sa.String(length=1000), nullable=True),
    sa.Column('texto_menu_assistencia', sa.String(length=1000), nullable=True),
    sa.Column('texto_sobre_loja', sa.String(length=1000), nullable=True),
    sa.Column('horario_funcionamento', sa.String(length=255), nullable=True),
    sa.Column('endereco_loja', sa.String(length=500), nullable=True),
    sa.Column('atendente_pagamento_telefone', sa.String(length=20), nullable=True),
    sa.Column('ia_habilitada', sa.Boolean(), nullable=True),
    sa.Column('pedido_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto_padrao_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao_loja')
    # ### end Alembic commands ###
