"""adiciona mensagem_processada (idempotencia webhook)

Revision ID: f8e1a22f08c0
Revises: 99e7e7787c8e
Create Date: 2026-08-25 19:23:05.908579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e1a22f08c0'
down_revision = '99e7e7787c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagem_processada',
    sa.Column('id_mensagem', sa.String(length=128), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('processada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_mensagem')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem_processada')
    # ### end Alembic commands ###
